name: Publish Docker Image

on:
  push:
    branches: [ master ]
  release:
    types:
      - published
        
jobs:

  build:
    if: "contains(github.event.head_commit.message, 'Docker image')"
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        uses: docker/login-action@v1.10.0
        with:
          #registry: ${{ secrets.DOCKER_USER }}/ghost_mki
          username: ${{ secrets.DOCKER_USER }}
          password:  ${{ secrets.DOCKER_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: |
            hypeitnow/ghost_mki:v1 
          file: ./docker/Dockerfile
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
          


        
